package parser.tokenizer

enum class Type(val regex: String) {
    WHITESPACE("([ \\t\\r])"),
    COMMENT("(#([^\\n]*))"),
    IMPORT_KEYWORD("(import)([^A-Za-z0-9_]{1})"),
    FN_KEYWORD("(fn)([^A-Za-z0-9_]{1})"),
    RETURN_KEYWORD("(return)([^A-Za-z0-9_]{1})"),
    IF_KEYWORD("(if)([^A-Za-z0-9_]{1})"),
    ELSE_KEYWORD("(else)([^A-Za-z0-9_]{1})"),
    ELIF_KEYWORD("(elif)([^A-Za-z0-9_]{1})"),
    WHILE_KEYWORD("(while)([^A-Za-z0-9_]{1})"),
    FOR_KEYWORD("(for)([^A-Za-z0-9_]{1})"),
    IN_KEYWORD("(in)([^A-Za-z0-9_]{1})"),
    BREAK_KEYWORD("(break)([^A-Za-z0-9_]{1})"),
    CONTINUE_KEYWORD("(continue)([^A-Za-z0-9_]{1})"),
    DEL_KEYWORD("(del)([^A-Za-z0-9_]{1})"),
    VAR_KEYWORD("(var)([^A-Za-z0-9_]{1})"),
    AND("(and)([^A-Za-z0-9_]{1})"),
    OR("(or)([^A-Za-z0-9_]{1})"),
    BOOLEAN("(true|false)([^A-Za-z0-9_]{1})"),
    NULL("(null)([^A-Za-z0-9_]{1})"),
    IDENTIFIER("([A-Za-z_][A-Za-z0-9_]*)"),
    QUOTE("(\"|')((?:\\\\\\1|(?!\\1).)*)(\\1)"),
    DOT("(\\.)([^0-9]{1})"),
    FLOAT("([0-9]*\\.[0-9]*)"),
    INTEGER("([0-9]+)"),
    LEFT_CURLY_BRACE("(\\{)"),
    RIGHT_CURLY_BRACE("(\\})"),
    LEFT_PARENTHESIS("(\\()"),
    RIGHT_PARENTHESIS("(\\))"),
    LEFT_SQUARE_BRACE("(\\[)"),
    RIGHT_SQUARE_BRACE("(\\])"),
    COMPARISON_OPERATOR("(==|!=|<=|>=|<|>)"),
    EQUALS("(=)"),
    MINUS_EQUALS("(-=)"),
    PLUS_EQUALS("(\\+=)"),
    COMMA("(,)"),
    SEMICOLON("(;)"),
    NEWLINE("(\\n+)([ \\n\\t\\r]*)"),
    COLON("(:)"),
    BANG("(!)"),
    PLUS_PLUS("(\\+{2})"),
    MINUS_MINUS("(\\-{2})"),
    PLUS("(\\+)"),
    MINUS("(\\-)"),
    ASTERISK("(\\*)"),
    DOUBLE_SLASH("(\\/\\/)"),
    SLASH("(\\/)"),
    CARET("(\\^)"),
    PERCENT("(\\%)"),
    END_OF_FILE("(?!)"),
    ;
}
