package parser.tokenizer

import java.util.regex.Pattern

enum class Type(val regex: Pattern) {
    WHITESPACE(Pattern.compile("""^[ \t\r]""")),
    COMMENT(Pattern.compile("""^((#([^\n]*))|((?s)/\*.*?\*/))""")),
    IMPORT_KEYWORD(Pattern.compile("""^import(?![A-Za-z0-9_`])""")),
    FN_KEYWORD(Pattern.compile("""^fn(?![A-Za-z0-9_`])""")),
    RETURN_KEYWORD(Pattern.compile("""^return(?![A-Za-z0-9_`])""")),
    IF_KEYWORD(Pattern.compile("""^if(?![A-Za-z0-9_`])""")),
    ELSE_KEYWORD(Pattern.compile("""^else(?![A-Za-z0-9_`])""")),
    ELIF_KEYWORD(Pattern.compile("""^elif(?![A-Za-z0-9_`])""")),
    WHILE_KEYWORD(Pattern.compile("""^while(?![A-Za-z0-9_`])""")),
    FOR_KEYWORD(Pattern.compile("""^for(?![A-Za-z0-9_`])""")),
    NOT_IN_KEYWORD(Pattern.compile("""^!in(?![A-Za-z0-9_`])""")),
    IN_KEYWORD(Pattern.compile("""^in(?![A-Za-z0-9_`])""")),
    BREAK_KEYWORD(Pattern.compile("""^break(?![A-Za-z0-9_`])""")),
    CONTINUE_KEYWORD(Pattern.compile("""^continue(?![A-Za-z0-9_`])""")),
    DEL_KEYWORD(Pattern.compile("""^del(?![A-Za-z0-9_`])""")),
    VAR_KEYWORD(Pattern.compile("""^var(?![A-Za-z0-9_`])""")),
    VAL_KEYWORD(Pattern.compile("""^val(?![A-Za-z0-9_`])""")),
    AS_KEYWORD(Pattern.compile("""^as(?![A-Za-z0-9_`])""")),
    GET_KEYWORD(Pattern.compile("""^get(?![A-Za-z0-9_`])""")),
    STRUCT_KEYWORD(Pattern.compile("""^struct(?![A-Za-z0-9_`])""")),
    STATIC_KEYWORD(Pattern.compile("""^static(?![A-Za-z0-9_`])""")),
    AND(Pattern.compile("""^and(?![A-Za-z0-9_`])""")),
    OR(Pattern.compile("""^or(?![A-Za-z0-9_`])""")),
    BOOLEAN(Pattern.compile("""^(true|false)(?![A-Za-z0-9_`])""")),
    NULL(Pattern.compile("""^null(?![A-Za-z0-9_`])""")),
    IDENTIFIER(Pattern.compile("""^(`?)[A-Za-z_][A-Za-z0-9_]*(\1)""")),
    QUOTE_START(Pattern.compile("""^(["'])((?:\\\1|\\\{|(?!\1).)*?)((?<!\\)\{)""")),
    QUOTE_MIDDLE(Pattern.compile("""^(})((?:\\\1|\\\{|}|.)*?)((?<!\\)\{)""")),
    QUOTE_END(Pattern.compile("""^(})(.*?)((?<!\\)["'])""")),
    QUOTE(Pattern.compile("""^(["'])((?:\\\1|.)*?)((?<!\\)\1)""")),
    FLOAT(Pattern.compile("""^[0-9]*\.[0-9]+""")),
    DOT_DOT(Pattern.compile("""^\.{2}""")),
    DOT(Pattern.compile("""^\.""")),
    INTEGER(Pattern.compile("""^[0-9]+""")),
    LEFT_CURLY_BRACE(Pattern.compile("""^\{""")),
    RIGHT_CURLY_BRACE(Pattern.compile("""^}""")),
    LEFT_PARENTHESIS(Pattern.compile("""^\(""")),
    RIGHT_PARENTHESIS(Pattern.compile("""^\)""")),
    LEFT_SQUARE_BRACE(Pattern.compile("""^\[""")),
    RIGHT_SQUARE_BRACE(Pattern.compile("""^]""")),
    COMPARISON_OPERATOR(Pattern.compile("""^(==|!=|<=|>=|<|>)""")),
    EQUALS(Pattern.compile("""^=""")),
    MINUS_EQUALS(Pattern.compile("""^-=""")),
    PLUS_EQUALS(Pattern.compile("""^\+=""")),
    COMMA(Pattern.compile("""^,""")),
    SEMICOLON(Pattern.compile("""^;""")),
    NEWLINE(Pattern.compile("""^\n+[ \n\t\r]*""")),
    COLON_COLON(Pattern.compile("""^:{2}""")),
    COLON(Pattern.compile("""^:""")),
    BANG(Pattern.compile("""^!""")),
    PLUS_PLUS(Pattern.compile("""^\+{2}""")),
    MINUS_MINUS(Pattern.compile("""^-{2}""")),
    PLUS(Pattern.compile("""^\+""")),
    MINUS(Pattern.compile("""^-""")),
    ASTERISK(Pattern.compile("""^\*""")),
    DOUBLE_SLASH(Pattern.compile("""^//""")),
    SLASH(Pattern.compile("""^/""")),
    CARET(Pattern.compile("""^\^""")),
    PERCENT(Pattern.compile("""^%""")),
    END_OF_FILE(Pattern.compile("""^?!""")),
    ;
}
