package parser.tokenizer

enum class Type(val regex: String) {
    WHITESPACE("([ \\t\\r])"),
    COMMENT("(#([^\\n]*))"),
    FN_KEYWORD("(fn)([^A-Za-z0-9_]{1})"),
    IF_KEYWORD("(if)([^A-Za-z0-9_]{1})"),
    KEYWORD("(import|fn|return|else|elif|while|for|in|break|continue|del)([^A-Za-z0-9_]{1})"),
    AND("(and)([^A-Za-z0-9_]{1})"),
    OR("(or)([^A-Za-z0-9_]{1})"),
    BOOLEAN("(true|false)([^A-Za-z0-9_]{1})"),
    NULL("(null)([^A-Za-z0-9_]{1})"),
    IDENTIFIER("([A-Za-z_][A-Za-z0-9_]*)"),
    QUOTE("(\"|')((?:\\\\\\1|(?!\\1).)*)(\\1)"),
    DOT("(\\.)([^0-9]{1})"),
    FLOAT("([0-9]*\\.[0-9]*)"),
    INTEGER("([0-9]+)"),
    LEFT_CURLY_BRACE("(\\{)"),
    RIGHT_CURLY_BRACE("(\\})"),
    LEFT_PARENTHESIS("(\\()"),
    RIGHT_PARENTHESIS("(\\))"),
    LEFT_SQUARE_BRACE("(\\[)"),
    RIGHT_SQUARE_BRACE("(\\])"),
    COMPARISON_OPERATOR("(==|!=|<=|>=|<|>)"),
    ASSIGN("(=|\\+=|-=)"),
    COMMA("(,)"),
    SEMICOLON("(;)"),
    NEWLINE("(\\n+)([ \\n\\t\\r]*)"),
    COLON("(:)"),
    BANG("(!)"),
    PLUS_PLUS("(\\+{2})"),
    MINUS_MINUS("(\\-{2})"),
    PLUS("(\\+)"),
    MINUS("(\\-)"),
    ASTERISK("(\\*)"),
    DOUBLE_SLASH("(\\/\\/)"),
    SLASH("(\\/)"),
    CARET("(\\^)"),
    PERCENT("(\\%)"),
    ;
}
